### PR TITLE
updated code new conditions/limits

### PR DESCRIPTION
**Pull request by edhinman**
Added if then statement to show if new detection condition names or detection quantitation limit types are identified from merged_results and detquantlim.

### CODE REVIEW

**Comment by jakevl** [comment]
I'm getting numeric factor levels printed when new combinations are present. Looks to be due to cbind (lines 88 & 116) which coerces to matrix.
Is that what you were trying to account for by setting stringsAsFactors=F? I think just using data.frame instead of cbind would do the trick. I don't think stringsAsFactors should matter either way in this case (since we're using merge to add levels instead of manually adding).

**Comment by edhinman** [comment]
Ahh... I modeled it after the "WARNING: New site type(s) encountered" code in autoValidateWQPsites function. Yes, I did add the stringsAsFactors=F to try to deal with the numeric issue.

**Comment by jakevl** [comment]
Looks good. Nice work.

**Comment by edhinman** [comment]
Yay! I'm glad it was a simple fix.

**Pull request merged**
